# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_submitted', models.DateTimeField()),
                ('text', models.TextField()),
                ('sentences', models.IntegerField()),
                ('words', models.IntegerField()),
                ('syllables', models.IntegerField()),
                ('characters', models.IntegerField()),
                ('polysyllables', models.IntegerField()),
                ('readability_index', models.FloatField()),
                ('fk_grade_level', models.FloatField()),
                ('ari', models.FloatField()),
                ('smog', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_date', models.DateTimeField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('website_url', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
