# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 20:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ta_web', '0002_auto_20170502_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ari',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='characters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='fk_grade_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='polysyllables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='readability_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='sentences',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='smog',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='syllables',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='words',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
